# Generated by Django 4.2.7 on 2023-12-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfflip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
    ]
